### ISSUE TITLE
周杰伦歌曲是不是未来都无法听了啊

### ISSUE THREAD

**Issue by njc0125** [nining377/dolby_beta#11]
我用旧版本的unblock music插件，还是能听的，更新版本后，周杰伦歌就下载不了了，是不是以后都没有这个功能了啊

最后还是感谢大佬的插件

**Comment by nining377** [comment]
应该都可以听，可以配合杜比大喇叭食用哦

**Comment by nining377** [comment]
应该都可以听，可以配合UnblockMusic Pro食用哦
