### ISSUE TITLE
3.0.0仍未修复targetSdk大于29时node无法运行的问题

### ISSUE THREAD

**Issue by aviraxp** [nining377/dolby_beta#112]
09-17 18:47:22.175 W/sh      (27252): type=1400 audit(0.0:1805): avc: denied { execute_no_trans } for path="/data/user/0/com.netease.cloudmusic/files/script/node" dev="dm-7" ino=401865 scontext=u:r:untrusted_app_29:s0:c14,c257,c512,c768 tcontext=u:object_r:app_data_file:s0:c14,c257,c512,c768 tclass=file permissive=0

**Comment by aviraxp** [comment]
这么看来，/data/user并不可以

**Comment by zhangsiyu0** [comment]
确实，还是要用旧版网易云或者刷那个selinux模块。

**Comment by nining377** [comment]
这我也没办法呀

**Comment by aviraxp** [comment]
能不能放模块的lib里面

**Comment by nining377** [comment]
> 能不能放模块的lib里面

node是二进制执行文件，并不是常规的jar，放到lib运行不起来

**Comment by yujincheng08** [comment]
> > 能不能放模块的lib里面
> 
> node是二进制执行文件，并不是常规的jar，放到lib运行不起来

我们说的是 apk 的 lib 不是 gradle 的 lib。以 so 文件形式存在。

**Comment by yujincheng08** [comment]
在 Android 12 下运行 lib 的 ELF 依然是被 selinux 规则允许的：
```
allow appdomain apk_data_file:dir { getattr ioctl lock open read search watch watch_reads };
allow appdomain apk_data_file:file { execute execute_no_trans getattr ioctl lock map open read watch watch_reads };
```

注意，都是 ELF 文件，所以 dlopen 一个 so 还是运行一个 so 都是 execute 和 execute_no_trans 规则。

**Comment by nining377** [comment]
> > > 能不能放模块的lib里面
> > 
> > 
> > node是二进制执行文件，并不是常规的jar，放到lib运行不起来
> 
> 我们说的是 apk 的 lib 不是 gradle 的 lib。以 so 文件形式存在。

我试试

**Comment by yujincheng08** [comment]
3.1.0 亲测可用。

**Comment by nining377** [comment]
> 3.1.0 亲测可用。

好嘞，那这个issue可以关啦
