### ISSUE TITLE
3.0版本

### ISSUE THREAD

**Issue by Mo-xiaolang** [nining377/dolby_beta#114]
3.0精简功能都没了，而且支持版本也没了

**Comment by nining377** [comment]
> 3.0精简功能都没了，而且支持版本也没了

精简功能还没来得及写，中秋后可能写得出来，支持目前4.3.1到最新版本

**Comment by Mo-xiaolang** [comment]
> > 3.0精简功能都没了，而且支持版本也没了
> 
> 精简功能还没来得及写，中秋后可能写得出来，支持目前4.3.1到最新版本

最新版8.5.30版本没法用，显示停止运行，重启几次都是。

**Comment by Charlotte0000** [comment]
为啥我最新版网易云连大喇叭设置选项都没看到😂

**Comment by HMLDXHZ** [comment]
> 为啥我最新版网易云连大喇叭设置选项都没看到😂

我的也是🥲

**Comment by kun526586** [comment]
> 为啥我最新版网易云连大喇叭设置选项没看到😂

我用的8.2.42正常

**Comment by HMLDXHZ** [comment]
我换8.2.42了，一样没用，可能因为我用的太极阴吧

**Comment by HMLDXHZ** [comment]
我安卓11 强行停止太极，强行停止网易云音乐 再打开 就出来了
