### ISSUE TITLE
3.0版本

### ISSUE THREAD

**Issue by sugar0818** [nining377/dolby_beta#115]
网易云音乐8.5.30版本在设置里面没看到大喇叭的设置按钮，用的是Lsposed框架

**Comment by nining377** [comment]
> 网易云音乐8.5.30版本在设置里面没看到大喇叭的设置按钮，用的是Lsposed框架

可能被网易云热修复影响，你清除一下网易云的数据即可

**Comment by Mo-xiaolang** [comment]
兄弟，你8.5.30版本可以用了吗？

**Comment by sugar0818** [comment]
能用了
