### ISSUE TITLE
[FR]加入专辑封面禁旋转功能

### ISSUE THREAD

**Issue by txyyh** [nining377/dolby_beta#116]
RT
可参考[这个](https://github.com/Henry-ZHR/cloudmusic_cover)

**Comment by nining377** [comment]
为啥会有这种奇怪的需求，不过会考虑的

**Comment by txyyh** [comment]
~~其实我还想要方形封面~~

这个开发难度太大，你直接弃了吧（

**Comment by nining377** [comment]
> ~其实我还想要方形封面~
> 
> 这个开发难度太大，你直接弃了吧（

23333333…我尽量

**Comment by nining377** [comment]
> ~其实我还想要方形封面~
> 
> 这个开发难度太大，你直接弃了吧（

你要的停转，方形图没办法弄
