### ISSUE TITLE
获取不到Cookie

### ISSUE THREAD

**Issue by Q2297045667** [nining377/dolby_beta#12]
无论是手机号登录还是QQ，微信微博等快捷登录都提示获取不到Cookie
网易云版本7.2.0
模块版本1.0.3

**Comment by Q2297045667** [comment]
7.1.80也不行，还有会打开失败

**Comment by Q2297045667** [comment]
打卡失败

**Comment by nining377** [comment]
晚点修复

**Comment by 2051783131** [comment]
现在新版本还是不可以😂

**Comment by nining377** [comment]
> 现在新版本还是不可以

只有手机登录才能获取cookie哦

**Comment by xhjxhk** [comment]
> > 现在新版本还是不可以
> 
> 只有手机登录才能获取Cookie哦

**依然無法過期cookie**

**Comment by nining377** [comment]
> > > 现在新版本还是不可以
> > 
> > 
> > 只有手机登录才能获取Cookie哦
> 
> **依然無法獲取cookie**

这就有点奇怪了，是否为太极呢？

**Comment by FrozenMum** [comment]
> > > > 现在新版本还是不可以
> > > 
> > > 
> > > 只有手机登录才能获取Cookie哦
> > 
> > 
> > **依然無法獲取cookie**
> 
> 这就有点奇怪了，是否为太极呢？

我用校园网也同样是获取cookie失败，但仅限于开启unblockmusic，报错显示

**Comment by nining377** [comment]
> > > > > 现在新版本还是不可以
> > > > 
> > > > 
> > > > 只有手机登录才能获取Cookie哦
> > > 
> > > 
> > > **依然無法獲取cookie**
> > 
> > 
> > 这就有点奇怪了，是否为太极呢？
> 
> 我用校园网也同样是获取cookie失败，但仅限于开启unblockmusic，报错显示句柄无效，语法错误

句柄无效？安卓哪来的句柄，那是Windows的吧

**Comment by FrozenMum** [comment]
> > > > > > 现在新版本还是不可以
> > > > > 
> > > > > 
> > > > > 只有手机登录才能获取Cookie哦
> > > > 
> > > > 
> > > > **依然無法獲取cookie**
> > > 
> > > 
> > > 这就有点奇怪了，是否为太极呢？
> > 
> > 
> > 我用校园网也同样是获取cookie失败，但仅限于开启unblockmusic，报错显示句柄无效，语法错误
> 
> 句柄无效？安卓哪来的句柄，那是Windows的吧



> > > > > > 现在新版本还是不可以
> > > > > 
> > > > > 
> > > > > 只有手机登录才能获取Cookie哦
> > > > 
> > > > 
> > > > **依然無法獲取cookie**
> > > 
> > > 
> > > 这就有点奇怪了，是否为太极呢？
> > 
> > 
> > 我用校园网也同样是获取cookie失败，但仅限于开启unblockmusic，报错显示句柄无效，语法错误
> 
> 句柄无效？安卓哪来的句柄，那是Windows的吧

报错就是这么写的，我也不知道●‿●

**Comment by nining377** [comment]
有无截图？

**Comment by d4renk** [comment]
> > > > 现在新版本还是不可以
> > > 
> > > 
> > > 只有手机登录才能获取Cookie哦
> > 
> > 
> > **依然無法獲取cookie**
> 
> 这就有点奇怪了，是否为太极呢？

**是太極，我無法獲取**
