### ISSUE TITLE
最新3.1.0版本当中，UnblockNeteaseMusic一直停止运行

### ISSUE THREAD

**Issue by sunbohuashishabi** [nining377/dolby_beta#126]
系统是安卓11，lsposed框架（6079）

**Comment by nining377** [comment]
> 系统是安卓11，lsposed框架（6079）

lsp有没有日志蹦出来呢？之前3.0.0是否正常？

**Comment by sunbohuashishabi** [comment]
> > 系统是安卓11，lsposed框架（6079）
> 
> lsp有没有日志蹦出来呢？之前3.0.0是否正常？
lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行

**Comment by sunbohuashishabi** [comment]
> > 系统是安卓11，lsposed框架（6079）
> 
> lsp有没有日志蹦出来呢？之前3.0.0是否正常？

lsp有没有日志蹦出来呢？之前3.0.0是否正常？
lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行

**Comment by sunbohuashishabi** [comment]
> > 系统是安卓11，lsposed框架（6079）
> 
> lsp有没有日志蹦出来呢？之前3.0.0是否正常？
lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行

**Comment by nining377** [comment]
> > > 系统是安卓11，lsposed框架（6079）
> > 
> > 
> > lsp有没有日志蹦出来呢？之前3.0.0是否正常？
> 
> lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
> 3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行

方便的话留下联系方式吧

**Comment by zhangsiyu0** [comment]
> > > 系统是安卓11，lsposed框架（6079）
> > 
> > 
> > lsp有没有日志蹦出来呢？之前3.0.0是否正常？
> 
> lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
> 3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行

32位的网易云8.5.30 可以正常使用。

**Comment by nining377** [comment]
> > > > 系统是安卓11，lsposed框架（6079）
> > > 
> > > 
> > > lsp有没有日志蹦出来呢？之前3.0.0是否正常？
> > 
> > 
> > lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
> > 3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行
> 
> 32位的网易云8.5.30 可以正常使用。

你们64位网易云是去哪里下载的？酷安上下的只有32位

**Comment by zhangsiyu0** [comment]
> > > > > 系统是安卓11，lsposed框架（6079）
> > > > 
> > > > 
> > > > lsp有没有日志蹦出来呢？之前3.0.0是否正常？
> > > 
> > > 
> > > lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
> > > 3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行
> > 
> > 
> > 32位的网易云8.5.30 可以正常使用。
> 
> 你们64位网易云是去哪里下载的？酷安上下的只有32位

小米应用商店。

**Comment by nining377** [comment]
> > > > > > 系统是安卓11，lsposed框架（6079）
> > > > > 
> > > > > 
> > > > > lsp有没有日志蹦出来呢？之前3.0.0是否正常？
> > > > 
> > > > 
> > > > lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
> > > > 3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行
> > > 
> > > 
> > > 32位的网易云8.5.30 可以正常使用。
> > 
> > 
> > 你们64位网易云是去哪里下载的？酷安上下的只有32位
> 
> 小米应用商店。

原来如此，我去下一个试试看

**Comment by sunbohuashishabi** [comment]
> > > > 系统是安卓11，lsposed框架（6079）
> > > 
> > > 
> > > lsp有没有日志蹦出来呢？之前3.0.0是否正常？
> > 
> > 
> > lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
> > 3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行
> 
> 方便的话留下联系方式吧

好的 QQ：2910988656

**Comment by sunbohuashishabi** [comment]
> > > > 系统是安卓11，lsposed框架（6079）
> > > 
> > > 
> > > lsp有没有日志蹦出来呢？之前3.0.0是否正常？
> > 
> > 
> > lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
> > 3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行
> 
> 32位的网易云8.5.30 可以正常使用。

我也是32位🥲

**Comment by untll** [comment]
> > > > > 系统是安卓11，lsposed框架（6079）
> > > > 
> > > > 
> > > > lsp有没有日志蹦出来呢？之前3.0.0是否正常？
> > > 
> > > 
> > > lsp没有蹦出日志，之前3.0.0正常，因为我用的是targetSDK 28的版本。
> > > 3.1.0不是说修复了targetSdk大于29时node无法运行的问题吗？然后我卸载后重新下了8.5.30的网易云，但UnblockNeteaseMusic一直停止运行
> > 
> > 
> > 32位的网易云8.5.30 可以正常使用。
> 
> 你们64位网易云是去哪里下载的？酷安上下的只有32位

我则是在豌豆荚下载的

**Comment by nining377** [comment]
该问题是由alpha版magisk阻塞了log造成的，如果安装的架构是相同但是仍然无法运行大喇叭的可自行排查一下
