### ISSUE TITLE
UnblockNeteaseMusic stop running

### ISSUE THREAD

**Issue by cc9014** [nining377/dolby_beta#127]
**ENV**
Device: Oneplus 8T
Magisk: 23.0
Riru: v26.1.2.r505.c20529bced
Riru-LSPosed: v1.5.3(5984)
UnblockNeteaseMusic: 3.1.1
NeteaseMusic: V8.5.40.113941

**Actual behaviour**
UnblockNeteaseMusic not running shows: 停止运行

**Comment by cc9014** [comment]
Solved, re-install UnblockNeteaseMusic 32bit... I am confusing why I should use 32bit apk :(

**Comment by nining377** [comment]
> Solved, re-install UnblockNeteaseMusic 32bit... I am confusing why I should use 32bit apk :(

Because the netease cloud music you installed is a 32-bit version.if you want to install the 64 bit version,please go to Xiaomi App store.

**Comment by cc9014** [comment]
> 
> 
> > Solved, re-install UnblockNeteaseMusic 32bit... I am confusing why I should use 32bit apk :(
> 
> Because the netease cloud music you installed is a 32-bit version，dolby_beta uses 32-bit or 64-bit depending on the host framework。If you want to install the 64-bit version,please go to Xiaomi App store.

Thank for your reply. I always download the app from coolapk, now I switch to 64bit netease cloud music. dolby beta works well~
