### ISSUE TITLE
最新3.1.1界面错误

### ISSUE THREAD

**Issue by Coconutat** [nining377/dolby_beta#132]
使用网易云版本：4.3.1 谷歌商店版
Xposed：EdXposed
安卓版本：8.0.0
机型：华为P10 （EMUI8）
错误描述：手机屏幕大小不太符合现在的手机大小，导致大喇叭3.1.1无法显示完整的界面。大喇叭也没法上下滑动。
附图。
![Screenshot_20211005-085451](https://user-images.githubusercontent.com/85353552/135943911-a98dbbf2-c926-48c3-bf71-1b53907d71f0.jpg)

**Comment by SekiBetu** [comment]
> 不懂就问，3.1.1在哪下载的，是有什么群组吗

https://github.com/nining377/dolby_beta/releases

**Comment by nining377** [comment]
> 使用网易云版本：4.3.1 谷歌商店版 Xposed：EdXposed 安卓版本：8.0.0 机型：华为P10 （EMUI8） 错误描述：手机屏幕大小不太符合现在的手机大小，导致大喇叭3.1.1无法显示完整的界面。大喇叭也没法上下滑动。 附图。 ![Screenshot_20211005-085451](https://user-images.githubusercontent.com/85353552/135943911-a98dbbf2-c926-48c3-bf71-1b53907d71f0.jpg)

emmmmmm应该是分辨率太低了

**Comment by nining377** [comment]
已修复
