### ISSUE TITLE
3.1.1

### ISSUE THREAD

**Issue by vifei** [nining377/dolby_beta#135]
![S11011-16402395](https://user-images.githubusercontent.com/63733508/136761436-3cf98916-0bf1-405c-b35c-b40edc0caa91.png)
关闭本地黑胶后会出现这种情况，打开后就会变好。
安卓11
魅族18
杜比大喇叭3.1.1
网易云8.5.30
设置如图
![S11011-16440437](https://user-images.githubusercontent.com/63733508/136761682-621fd240-fd8a-4889-9298-0b9a0f67f27c.png)
![S11011-16403380](https://user-images.githubusercontent.com/63733508/136761715-d53c0d0b-c242-4d00-873b-34da5dea5e18.png)

**Comment by 211906695** [comment]
框架是lsp1.6.0
