### ISSUE TITLE
内置模块问题

### ISSUE THREAD

**Issue by luoxingran** [nining377/dolby_beta#138]
采用xpatch lspatch
均无法进行解灰，但是模块能够运行
能出个专版么

**Comment by luoxingran** [comment]
需要个xpatch能解灰的模块就行了32位的un会停止运行发自我的荣耀手机-------- 原始邮件 --------发件人： nining377 ***@***.***>日期： 2021年10月19日周二 上午9:17收件人： nining377/dolby_beta ***@***.***>抄送： luoxingran ***@***.***>, Author ***@***.***>主    题： Re: [nining377/dolby_beta] 内置模块问题 (Issue #138)

你想要什么版本的网易云？

**Comment by nining377** [comment]
> 需要个xpatch能解灰的模块就行了32位的un会停止运行发自我的荣耀手机-------- 原始邮件 --------发件人： nining377 ***@***.***>日期： 2021年10月19日周二 上午9:17收件人： nining377/dolby_beta ***@***.***>抄送： luoxingran ***@***.***>, Author ***@***.***>主 题： Re: [nining377/dolby_beta] 内置模块问题 (Issue #138) 你想要什么版本的网易云？ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

试试吧，不要安装杜比大喇叭，单独安装它就好了，这是支持一起听，功能相对完整又不会太臃肿的版本
https://www.lanzouw.com/b0crkhyzg
密码:3qvw

**Comment by luoxingran** [comment]
> > 需要个xpatch能解灰的模块就行了32位的un会停止运行发自我的荣耀手机-------- 原始邮件 --------发件人： nining377 _**@**_._**>日期： 2021年10月19日周二 上午9:17收件人： nining377/dolby_beta _**@**_.**_>抄送： luoxingran _**@**_._**>, Author _**@**_.**_>主 题： Re: [nining377/dolby_beta] 内置模块问题 (Issue #138) 你想要什么版本的网易云？ —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
> 
> 试试吧，不要安装杜比大喇叭，单独安装它就好了，这是支持一起听，功能相对完整又不会太臃肿的版本 https://www.lanzouw.com/b0crkhyzg 密码:3qvw

**Comment by luoxingran** [comment]
没问题了
