### ISSUE TITLE
能否增加可以自己配置代理链接的功能？

### ISSUE THREAD

**Issue by zy199226** [nining377/dolby_beta#14]
希望能增加这个功能，可以用自己的服务器上面的代理服务，然后应该就可以拥有播放高音质版权音乐的能力吧？

**Comment by nining377** [comment]
如果你打算使用自己的服务器进行代理，可以尝试使用UnblockMusic Pro把本地运行脚本的代码去除并把指向本地的地址[127.0.0.1:23338](https://github.com/nining377/UnblockMusicPro_Xposed/blob/df3f44235eec81c5a95dc6a69a157f5b4069fd37/app/src/main/java/com/raincat/unblockmusicpro/HTTPHook.java#L114)改成你的远程服务器地址+端口号

**Comment by zy199226** [comment]
> 如果你打算使用自己的服务器进行代理，可以尝试使用UnblockMusic Pro把本地运行脚本的代码去除并把指向本地的地址[127.0.0.1:23338](https://github.com/nining377/UnblockMusicPro_Xposed/blob/df3f44235eec81c5a95dc6a69a157f5b4069fd37/app/src/main/java/com/raincat/unblockmusicpro/HTTPHook.java#L114)改成你的远程服务器地址+端口号

好的，谢谢了
