### ISSUE TITLE
提示用户校验失败

### ISSUE THREAD

**Issue by ChellyL** [nining377/dolby_beta#15]
beta版会提示用户校验失败，
我也安装了大喇叭，尝试使用UnblockNeteaseMusic代理功能，并使用自己的服务器（已测试服务器正常）同样提示用户校验失败
UnblockMusicPro_Xposed则可以正常使用

**Comment by nining377** [comment]
大喇叭β版无服务器，所以不会检验用户，你可以看看是否为其他问题
