### ISSUE TITLE
3.3.5侧边栏精简无作用

### ISSUE THREAD

**Issue by Termux000001** [nining377/dolby_beta#157]
🌝🌝

**Comment by nining377** [comment]
有效果的，请提供网易云版本和xposed环境，如果可以，请提供有无日志

**Comment by xushet** [comment]
> 有效果的，请提供网易云版本和xposed环境，如果可以，请提供有无日志

网易云4.3.5 Google play版
lsp1.6.3（6212）
失效，点击“精简侧边栏”会导致网易云马上黑屏并停止运行

**Comment by nining377** [comment]
> > 有效果的，请提供网易云版本和xposed环境，如果可以，请提供有无日志
> 
> 网易云4.3.5 Google play版 lsp1.6.3（6212） 失效，点击“精简侧边栏”会导致网易云马上黑屏并停止运行

不支持435，谷歌版请使用431

**Comment by JohnnyEthical** [comment]
> 

大佬，现在431、999等好多版本都无法登陆，只有435能够勉强登录。
另，是不是用过了之后，就没办法实现软件之间的分享了啊？改签名什么的方法能够实现吗？
