### ISSUE TITLE
3.3.5版本打开网易云音乐后提示数据库操作失败

### ISSUE THREAD

**Issue by LinnyR** [nining377/dolby_beta#158]
网易云版本7.3.28
手机型号红米K30pro
系统版本miui12.5

我没找到能从哪里看日志哭![Screenshot_2021-11-05-23-20-24-629_com.netease.cloudmusic.jpg](https://user-images.githubusercontent.com/38827394/140535094-7dbc6ed7-a5e5-4e27-b669-039fc1a738cf.jpg)

**Comment by nining377** [comment]
这不是大喇叭弹出来的，你是否降级安装了网易云？

**Comment by LinnyR** [comment]
> 这不是大喇叭弹出来的，你是否降级安装了网易云？

啊这。。原来是这样，我装了核心破解，可能降级安装出问题了，谢谢大佬提醒～
