### ISSUE TITLE
关于此软件与您修改的音量增强器的一些疑问

### ISSUE THREAD

**Issue by rhjdvsgsgks** [nining377/dolby_beta#16]
1. 两者都是出自您之手，且都不需要服务器，是否可以说此软件是您改的增强器的“续作”
2. 都不需要服务器，为什么增强器改可以“获取高音质”(或者说有这个开关)，而此软件不能

**Comment by nining377** [comment]
1、可以说是也可以说不是，你可以在大喇叭里看到大量增强器继承下来的代码，但是大喇叭基于增强器已经做了大幅度改动，hook点已经基本上完全不同于增强器，功能也比增强器要更多
2、我修改的增强器并非不需要服务器，而是在借鉴了[nondanee/UnblockNeteaseMusic](https://github.com/nondanee/UnblockNeteaseMusic)之后写的本地服务，所以如果喜欢精简可以只用大喇叭，如果还希望无版权代理可以配合UnblockMusic Pro
