### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by fyeason** [nining377/dolby_beta#160]
云音乐版本：7.2.10.782837
大喇叭版本：3.3.5
运行环境：太极阴
系统为originOS，安卓11，无root
本地黑胶可用，可以在线完整听，但如果下载则提示“版权方要求，当前资源须付费使用。”
正常吗？

**Comment by nining377** [comment]
> 云音乐版本：7.2.10.782837 大喇叭版本：3.3.5 运行环境：太极阴 系统为originOS，安卓11，无root 本地黑胶可用，可以在线完整听，但如果下载则提示“版权方要求，当前资源须付费使用。” 正常吗？

下版本修复

**Comment by nining377** [comment]
已修复

**Comment by fyeason** [comment]
> 已修复

emmm现在在线听的也变成试听30秒版本了，下载的也是30秒试听😂

**Comment by nining377** [comment]
> > 已修复
> 
> emmm现在在线听的也变成试听30秒版本了，下载的也是30秒试听😂

好的_(:D)∠)_这匹配是个迷，我今天再看看
