### ISSUE TITLE
建议网易云音乐在后台时不要显示运行成功的Toast

### ISSUE THREAD

**Issue by CCRcmcpe** [nining377/dolby_beta#169]
目前，没开网易云的时候也总是冷不丁地出现“UnblockNeteaseMusic运行成功”。
https://github.com/nining377/dolby_beta/blob/6869b47ae1e931b30ee137cc93824b8107e13ef9/app/src/main/java/com/raincat/dolby_beta/helper/ScriptHelper.java#L158

**Comment by nining377** [comment]
频繁跳出来说明网易云运存被回收了（它本身吃的运存比微信都离谱），node是挂载在网易云上的，网易云挂掉脚本也会挂掉，在重启脚本运行成功肯定就会有提示，驳回该提议，如果你有这个需求可以自己打包，反正都是开源的
