### ISSUE TITLE
你好，关于自助打卡的问题。

### ISSUE THREAD

**Issue by WhiteAlbum-w** [nining377/dolby_beta#17]
我的手机在填写完cookie之后，由于这个太长，导致界面拉伸太多，以至于无法点击确定。能修改一下吗，谢谢。

**Comment by WhiteAlbum-w** [comment]
我的手机是小米mix2s。

**Comment by nining377** [comment]
已经修复过一次了呀，还会超长吗？

**Comment by WhiteAlbum-w** [comment]
我昨天晚上设置的，是超长了。我的app是最新版的。

**Comment by WhiteAlbum-w** [comment]
> 已经修复过一次了呀,还会超长吗?
嗯嗯，还是会超长，我检查了版本，是最新版的软件。

**Comment by Zy143L** [comment]
这边也检查了下 还是会超长
K20Pro 使用版本：1.0.5
@nining377

**Comment by nining377** [comment]
> 这边也检查了下 还是会超长
> K20Pro 使用版本：1.0.5
> @nining377

已修复
