### ISSUE TITLE
求一个能适配网易云极速版的版本

### ISSUE THREAD

**Issue by Rcrusade** [nining377/dolby_beta#173]
极速版比较简洁不用折腾，能适配大喇叭的话就能解灰了，两全其美岂不妙哉

**Comment by luoxingran** [comment]
上上个版本就适配了

**Comment by Rcrusade** [comment]
谢大佬指导搞定了，还有一个问题，app打开歌每次只能听一首且只能听一次，然后切其他歌没反应，切进度条没反应，必须退出极速版再进，大喇叭版本是3.3.9，手机版本安卓5.1.1

**Comment by nining377** [comment]
> 谢大佬指导搞定了，还有一个问题，app打开歌每次只能听一首且只能听一次，然后切其他歌没反应，切进度条没反应，必须退出极速版再进，大喇叭版本是3.3.9，手机版本安卓5.1.1

应该是内存不够了，等我改一下好了…

**Comment by Rcrusade** [comment]
期待ヽ(✿ﾟ▽ﾟ)ノ
