### ISSUE TITLE
通过 Xposed Tool 安装的用不了

### ISSUE THREAD

**Issue by gauzeehom** [nining377/dolby_beta#18]
网易云音乐 Play版 V4.3.1

**Comment by nining377** [comment]
不知道Xposed Tool是啥

**Comment by gauzeehom** [comment]
https://github.com/WindySha/Xpatch
看来用的人不多，忽略这个问题吧

**Comment by nining377** [comment]
> https://github.com/WindySha/Xpatch
> 看来用的人不多，忽略这个问题吧

好吧，感觉好厉害的样子，但是没有测试过兼容性，所以还是建议使用taichi等常见的免root框架运行本模块
