### ISSUE TITLE
UnblockNeteaseMusic产生致命错误

### ISSUE THREAD

**Issue by Bogersu** [nining377/dolby_beta#185]
Error: getaddrinfo ENOTFOUND music.163.com
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (dns.js:74:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'music.163.com'
}

三星note10，oneui3.1，安卓11，极光官改。
Magisk-Zygisk，lsposed-1.6.3 (6243) - Zygisk
网易云音乐7.3.28，用过好几个版本都出现这样的错误

**Comment by nining377** [comment]
一般翻墙就会这样

**Comment by nicangtianws01** [comment]
> 一般翻墙就会这样

但是没有fq也会这样

**Comment by nining377** [comment]
> > 一般翻墙就会这样
> 
> 但是没有fq也会这样

不影响的话可以不理，如果有问题可以去脚本那边提一下issue
