### ISSUE TITLE
歌曲添加到歌单的时候会出现 "服务器发生错误 ( code:521 )"

### ISSUE THREAD

**Issue by LKoiJZ** [nining377/dolby_beta#209]
无版权的灰色歌曲基本都会出现该问题，无论是下载时添加到歌单还是主动收藏，该情况在之前是可行的

有版权的歌曲在下载时添加到歌单会出现该问题，但是主动收藏时不会出现，在歌单内下载时会概率出现下载失败的问题，再次下载时会成功

网易云音乐版本 : 8.0.10
大喇叭版本 : 3.3.9

**Comment by luoxingran** [comment]
脚本的问题

**Comment by LKoiJZ** [comment]
> 脚本的问题

重新释放脚本也还是同样的问题 :(
