### ISSUE TITLE
网易云8.7.01无法生效

### ISSUE THREAD

**Issue by living-alive** [nining377/dolby_beta#219]
如题……

**Comment by living-alive** [comment]
不用回了

**Comment by mionmiao** [comment]
启动时会提示运行成功，但是设置中不显示模块，不过音源代理可以起作用。

**Comment by TroyLin0218** [comment]
+1
运行时会显示运行成功，但是设置项没了，自动打卡也没有辣，作者大大还更新吗？

**Comment by luoxingran** [comment]
> +1 运行时会显示运行成功，但是设置项没了，自动打卡也没有辣，作者大大还更新吗？

已完成配适

**Comment by V-arc** [comment]
> > +1 运行时会显示运行成功，但是设置项没了，自动打卡也没有辣，作者大大还更新吗？
> 
> 已完成配适

8.7.02 也这样的情况，运行成功，但是精简没有了，设置里也没有入口。

**Comment by luoxingran** [comment]
> > > +1 运行时会显示运行成功，但是设置项没了，自动打卡也没有辣，作者大大还更新吗？
> > 
> > 
> > 已完成配适
> 
> 8.7.02 也这样的情况，运行成功，但是精简没有了，设置里也没有入口。

已经提交分支合并，自己去看，我发了release

**Comment by huangge666** [comment]
> > > > +1 运行时会显示运行成功，但设置项也没有了，自动打卡没有辣，作者还大更新吗？
> > > 
> > > 
> > > 已完成配适
> > 
> > 
> > 8.7.02 也这样的情况，运行成功，但是没有了，设置里也没有入口。
> 
> 已经提交了分支，合并到了，我发布了

你好，我下载了您的 3.4.0bate3 版本内的 3.4.0与3.3.9 在设置内都未找到 大喇叭的设置
网易云版本：8.7.01
MIUI13：13.0.3
Android 12

**Comment by luoxingran** [comment]
提示重启次数过多了么，由于与签名不一样可能用不了

**Comment by luoxingran** [comment]
> > > > > +1 运行时会显示运行成功，但设置项也没有了，自动打卡没有辣，作者还大更新吗？
> > > > 
> > > > 
> > > > 已完成配适
> > > 
> > > 
> > > 8.7.02 也这样的情况，运行成功，但是没有了，设置里也没有入口。
> > 
> > 
> > 已经提交了分支，合并到了，我发布了
> 
> 你好，我下载了您的 3.4.0bate3 版本内的 3.4.0与3.3.9 在设置内都未找到 大喇叭的设置 网易云版本：8.7.01 MIUI13：13.0.3 Android 12 太极阴

不支持太极签名的问题

**Comment by huangge666** [comment]
> > > > > > +1 运行时会显示运行成功，但设置项也没有了，自动打卡没有辣，作者还大更新吗？
> > > > > 
> > > > > 
> > > > > 已完成配适
> > > > 
> > > > 
> > > > 8.7.02 也这样的情况，运行成功，但是没有了，设置里也没有入口。
> > > 
> > > 
> > > 已经提交了分支，合并到了，我发布了
> > 
> > 
> > 你好，我下载了您的 3.4.0bate3 版本内的 3.4.0与3.3.9 在设置内都未找到 大喇叭的设置 网易云版本：8.7.01 MIUI13：13.0.3 Android 12 太极阴
> 
> 不支持太极签名的问题

这样啊，请问目前有支持我当前环境版本的模块吗？
