### ISSUE TITLE
无版权音乐播放问题

### ISSUE THREAD

**Issue by eb66** [nining377/dolby_beta#23]
既然该版本已不支持播放无版权歌曲，那可否在播放无版权音乐时恢复为网易官方的模式，有些手动点击无版权的音乐，官方可自动切换为有版权的其它版本。

**Comment by nining377** [comment]
杜比没有处理到相关的逻辑呀，你点没版权音乐的所有逻辑是由网易云处理的

**Comment by eb886** [comment]
> 杜比没有处理到相关的逻辑呀，你点没版权音乐的所有逻辑是由网易云处理的

若不开启杜比，点击没版权音乐，若网易有其他音源（此时歌不会变灰）可自动切换，若是灰色歌曲，网易会弹出一个窗口告知没版权。但开启杜比在不配合unblock的情况下，点击没版权音乐，播放会切到此歌曲，但并不会播放。而且在歌单或其它列表播放时，遇到没版权的网易官方会自动跳过，而开启杜比就会直接卡住。

**Comment by eb886** [comment]
> 杜比没有处理到相关的逻辑呀，你点没版权音乐的所有逻辑是由网易云处理的

![IMG_20200905_231320.jpg](https://user-images.githubusercontent.com/65633189/92308140-2e8bc700-ef61-11ea-859b-0a7a4c442781.jpg)![IMG_20200905_231338.jpg](https://user-images.githubusercontent.com/65633189/92308151-3a778900-ef61-11ea-874b-39beb2372157.jpg)

**Comment by nining377** [comment]
已经修复，不要打钩不变灰即可自动跳过无版权音乐
