### ISSUE TITLE
Using lspatch to package 3.5.0 and 8.7.46/8.7.65,the module is not functioning properly

### ISSUE THREAD

**Issue by avenir2027** [nining377/dolby_beta#250]
Using lspatch to package 3.5.0 and 8.7.46/8.7.65,the VIP song just doesn't show that it needs VIP anymore,in fact,It doesn't actually play the full song.

**Comment by nining377** [comment]
There is no time to deal with lspatch. As you can see, the new version is not stable enough. I will issue the lspatch version after it is stable

**Comment by nining377** [comment]
There is no time to deal with lspatch. As you can see, the new version is not stable enough. I will issue the lspatch version after it is stable
