### ISSUE TITLE
cannot read propterties of undefined(reading 'find')

### ISSUE THREAD

**Issue by yihao0628** [nining377/dolby_beta#259]
问题如图
安卓版本:11
lsposed版本: 1.8.3zygisk
机型:红米note10pro
大喇叭版本:3.5.3
网易云版本:7.3.28.408871
已知恢复默认源并重新释放脚本无效，音乐播放貌似正常，但不知道换源是否成功

![Screenshot_2022-06-26-10-46-58-846_tw nekomimi nekogram](https://user-images.githubusercontent.com/75688855/175797285-50d2f23e-a1ce-4601-9bff-2b97f59543a3.jpg)

**Comment by nining377** [comment]
其实已经正常，不想被通知的可以关了警告继续用
