### ISSUE TITLE
请问能适配网易云音乐极速版吗？

### ISSUE THREAD

**Issue by snowoneyebrow** [nining377/dolby_beta#26]
我是在使用这个项目时看到的：https://github.com/ndroi/easy163

> 推荐：
网易云官方推出的 网易云极速版 [https://mip.onlinedown.net/soft/1225624.htm]
官网推出后不久下架，此版本网易云功能简单稳定，与 easy163 兼容良好

感觉用起来比较好 可惜您的插件不能对这个软件进行页面精简 希望您能抽空适配一下 谢谢！

**Comment by nining377** [comment]
精简版与6.0.0版本差异不大，可以直接使用6.0.0版本哦
