### ISSUE TITLE
皮肤出错

### ISSUE THREAD

**Issue by pubproprietary** [nining377/dolby_beta#261]
更换皮肤是出现错误，甚至有时候默认也不行

**Comment by nining377** [comment]
反馈请携带网易云版本号，Xposed环境以及版本等必要前置条件

**Comment by pubproprietary** [comment]
噢，我用的是最新的内置版，不过自己按教程做了一个，能用了

**Comment by pubproprietary** [comment]
https://wwu.lanzouw.com/ixWQJ06wupnc
