### ISSUE TITLE
未知错误

### ISSUE THREAD

**Issue by me-www** [nining377/dolby_beta#262]
使用时模块显示未知错误，类似直接断网，加载不出来其他板块，但可以放歌（点的私人FM，不用加载页面）
![Screenshot_2022_0703_163013](https://user-images.githubusercontent.com/82072100/177032590-dd98ada9-7463-45f2-99a3-ebeecbbea2fb.png)
![Screenshot_2022_0703_162017](https://user-images.githubusercontent.com/82072100/177032592-ed91b1ef-a41b-419f-8f72-08621f20ea1e.png)
![Screenshot_2022_0703_162039](https://user-images.githubusercontent.com/82072100/177032595-a774c3d5-ffec-4e98-abab-db70d4aa43ac.png)

**Comment by nining377** [comment]
你可能覆盖安装了不同版本的网易云，可以尝试清除数据或者卸载重装

**Comment by me-www** [comment]
> 你可能覆盖安装了不同版本的网易云，可以尝试清除数据或者卸载重装
我尝试改了不同网易云版本（均卸载重装并清除了卸载残留），结果都不行。使用杜比大喇叭的时候连第一次登录都不行；当模块关闭时，一切正常；但有一个特殊情况，当在关闭模块状态下，把歌单加载出来；然后打开模块，重启网易云，虽然仍旧显示未知错误（也类似不能联网），但已加载出来的歌单里的歌可以播放（又可以联网）
目前我用的太极承影9.1 ; 网易云6.0.0 ；杜比大喇叭 3.5.3（3.5.0和3.5.2也一样的情况）

**Comment by nining377** [comment]
> 

不建议使用太极，它无法很好的解决内联函数的hook，这将导致很多钩子只挂了一半或者干脆没生效，你可以选择更稳定的基于LSPatch打包的内嵌版本
