### ISSUE TITLE
脚本发生错误？

### ISSUE THREAD

**Issue by Mc-user1688** [nining377/dolby_beta#264]
![Screenshot_20220705-212251_Pixel 启动器](https://user-images.githubusercontent.com/73388367/177340230-6e527e8a-3778-418c-932b-4c353bf05700.png)
我不理解

**Comment by Mc-user1688** [comment]
然后部分歌曲转出来的有问题

**Comment by nining377** [comment]
匹配错误是正常现象，如果不是大面积歌曲失效或匹配失败，我没任何可修的办法

**Comment by Mc-user1688** [comment]
还真是有些歌曲匹配不对

**Comment by nining377** [comment]
> 还真是有些歌曲匹配不对

请看[README.md](https://github.com/nining377/dolby_beta/blob/master/README.md#%E6%A8%A1%E5%9D%97%E5%B7%A5%E4%BD%9C%E5%8E%9F%E7%90%86%E4%B8%BA%E9%9F%B3%E6%BA%90%E6%9B%BF%E6%8D%A2%E8%80%8C%E9%9D%9E%E7%A0%B4%E8%A7%A3%E6%89%80%E4%BB%A5%E5%8D%95%E6%9B%B2%E4%BB%98%E8%B4%B9%E4%B8%8E%E6%97%A0%E7%89%88%E6%9D%83%E6%AD%8C%E6%9B%B2%E6%9C%89%E5%87%A0%E7%8E%87%E5%8C%B9%E9%85%8D%E9%94%99%E8%AF%AF%E7%9C%9F%E5%BF%83%E6%94%AF%E6%8C%81%E6%AD%8C%E6%89%8B%E8%AF%B7%E4%BB%98%E8%B4%B9)
