### ISSUE TITLE
安卓12，lspatch版网易云更新8.7.90内测版后闪退，回退至本来正常的8.7.87问题遗留

### ISSUE THREAD

**Issue by LeapRay** [nining377/dolby_beta#266]
如题，因为太极阴不支持目前版本的网易云，使用的是lspatch版，在更新8.7.90之前一切正常；更新后出现闪退现象，且如果安装后首次打开，模块通知“无法找到downloadtransfer类”；在登录账号后会闪退，且通知“无法找到Cookie类”；此时通知栏出现播放栏，可以选择歌曲但无法进入。

清除数据重新安装之前正常的上一版本8.7.87亦出现上述现象。

**Comment by nining377** [comment]
暂时关闭其他作用于网易云的模块只保留大喇叭，清除数据后重试，如无问题再把其他模块打开

**Comment by LeapRay** [comment]
> 暂时关闭其他作用于网易云的模块只保留大喇叭，清除数据后重试，如无问题再把其他模块打开

感谢解答，但诸如清除数据、重启、关闭模块之类的操作均无效。而且教程视频似乎没有

> libnode.so放到网易云对应文件夹下arm64-v8a目录

这一步骤，无论我是否加上这一步骤，均会产生上述闪退现象，只不过不再提示“无法找到downloadtransfer类”报错。

同时，在之前的情况下，模块不会通知“运行成功”，进入设置也会显示“杜比大喇叭停止运行”，但实际上可以正常使用；而当前情况是，模块会通知“运行成功”，但是会立刻闪退。

**Comment by nining377** [comment]
> > 暂时关闭其他作用于网易云的模块只保留大喇叭，清除数据后重试，如无问题再把其他模块打开
> 
> 感谢解答，但诸如清除数据、重启、关闭模块之类的操作均无效。而且教程视频似乎没有
> 
> > libnode.so放到网易云对应文件夹下arm64-v8a目录
> 
> 这一步骤，无论我是否加上这一步骤，均会产生上述闪退现象，只不过不再提示“无法找到downloadtransfer类”报错。 同时，在之前的情况下，模块不会通知“运行成功”，进入设置也会显示“杜比大喇叭停止运行”，但实际上可以正常使用；而当前情况是，模块会通知“运行成功”，但是会立刻闪退。

8.7.90暂未适配

**Comment by LeapRay** [comment]
> 8.7.90暂未适配

其实我清除数据、卸载再回退到本来正常使用的8.7.87版本，也会有同样的现象……

**Comment by luoxingran** [comment]
> > 8.7.90暂未适配
> 
> 其实我清除数据、卸载再回退到本来正常使用的8.7.87版本，也会有同样的现象……

用8.7.86以下的新版有问题，等更新

**Comment by LeapRay** [comment]
> 用8.7.86以下的新版有问题，等更新

好的好的，多谢解答！
