### ISSUE TITLE
安卓12L lsposed+zygisk 报错

### ISSUE THREAD

**Issue by 1NO-NAME1** [nining377/dolby_beta#268]
![Screenshot_20220710-143312_网易云音乐](https://user-images.githubusercontent.com/97385339/178134287-28c480e2-d752-4e81-a146-79b484b74305.png)
[LSPosed_2022-07-10T14_40_31.587.zip](https://github.com/nining377/dolby_beta/files/9078577/LSPosed_2022-07-10T14_40_31.587.zip)

**Comment by 1NO-NAME1** [comment]
网易云版本6.0.0 ，模块为3.5.4版本

**Comment by luoxingran** [comment]
能用就不用管
