### ISSUE TITLE
勾选“本地黑胶”后，无法保存封面

### ISSUE THREAD

**Issue by y4kumo** [nining377/dolby_beta#27]
版本：
	dolby_beta： v 1.0.6
	网抑云: 6.4.3, 7.0.20, 7.2.0

平台: android 10

错误描述：勾选“本地黑胶”后，提示封面保存成功，实则保存的文件为200b的bmp空文件?相册里有这个文件，但无法读取。

测试了play4.3.1版，和6.4.3, 7.0.20, 7.2.0。
play4.3.1可能适配的原因，可以保存，保存后图片正常，6.4.3, 7.0.20, 7.2.0全部保存的为空文件。
取消勾选“本地黑胶”，图片可正常保存。

**Comment by y4kumo** [comment]
测试时以禁用其他网抑云模块。

**Comment by nining377** [comment]
经测试无法复现，请在保存图片后查看xposed日志中是否有dolby相关的错误日志

**Comment by nining377** [comment]
已修复
