### ISSUE TITLE
354大喇叭搭配网易云lite版，每次播放或者切歌，就提示错误

### ISSUE THREAD

**Issue by j4Uq** [nining377/dolby_beta#271]
![Screenshot_20220713-131456_网易云音乐](https://user-images.githubusercontent.com/6436073/178656126-c37356e6-f18d-4334-a651-f7d0235418bd.png)
云音乐lite版下载
https://wwi.lanzoup.com/iXfyh07rsr1g

**Comment by luoxingran** [comment]
能放就别管

**Comment by nining377** [comment]
如果不想看到警告提示可以在设置里关掉
