### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by m4536** [nining377/dolby_beta#272]
![Screenshot_20220718-104152](https://user-images.githubusercontent.com/109494291/179438229-c24eed90-bef4-41a6-8cd1-4b2fce4bd154.png)

**Comment by luoxingran** [comment]
没黑胶的开黑胶，然后关闭hook提示

**Comment by m4536** [comment]
开黑胶要钱的嘛


lin ***@***.***> 于 2022年7月18日周一 16:58写道：

**Comment by nining377** [comment]
怎么那么多人提这个issue，下个版本我关掉脚本提示算了…
