### ISSUE TITLE
关于网易云删除灰色歌曲问题的一个想法

### ISSUE THREAD

**Issue by zyyk78** [nining377/dolby_beta#273]
请问现在网易云大范围删除灰色歌曲
突然有这么一个想法

可不可以在未来加入一个歌曲--播放链接本地列表（我可以自己编辑）然后可以套其他歌的皮？？

这样也可以手动调整错配问题

**Comment by nining377** [comment]
> 请问现在网易云大范围删除灰色歌曲 突然有这么一个想法
> 
> 可不可以在未来加入一个歌曲--播放链接本地列表（我可以自己编辑）然后可以套其他歌的皮？？
> 
> 这样也可以手动调整错配问题

这个功能门槛太高了不适合大部分人，你可以尝试自己做一下提交pr
