### ISSUE TITLE
大佬你好，网抑云更新到8.0了

### ISSUE THREAD

**Issue by liuhaofay** [nining377/dolby_beta#28]
大佬你好，网抑云更新到8.0了

**Comment by nining377** [comment]
> 大佬你好，网抑云更新到8.0了

好的，目前已知的问题是小红点无法去除，其他的功能都比较正常，已经适配好了哦，至于侧边栏emmmmmm……还不想动的样子

**Comment by 1955782864** [comment]
适配8.0了吗？模块要不要更新

**Comment by nining377** [comment]
> 适配8.0了吗？模块要不要更新

嗯，晚一些会更新的
