### ISSUE TITLE
侧边栏精简失效8.0版本

### ISSUE THREAD

**Issue by 209650024** [nining377/dolby_beta#29]
实测侧边栏精简失效，希望大佬可以修复一下

**Comment by nining377** [comment]
从7.1.30开始就放弃适配精简侧边栏功能了哦

**Comment by nining377** [comment]
从7.3.10开始就放弃适配精简侧边栏功能了哦

**Comment by 209650024** [comment]
好的👌🏻了解了

**Comment by nining377** [comment]
> 好的👌🏻了解了

因为7.3.10以后的版本侧边栏变成了一个列表，里面的View是复用的，并不能单独把某个项去除，还需要再看看有什么其他方式挂上钩子

**Comment by 209650024** [comment]
这样，还有一个就是我打开300首功能是会闪退或者无提示（也就是不生效），不知道是什么问题。

**Comment by nining377** [comment]
> 这样，还有一个就是我打开300首功能是会闪退或者无提示（也就是不生效），不知道是什么问题。

可以重新登录试试
