### ISSUE TITLE
本地黑胶

### ISSUE THREAD

**Issue by T9041** [nining377/dolby_beta#30]
网易云7.2.21，大喇叭1.0.8，前几天用edxp时显示黑胶vip，后来又显示年费黑胶，今天换成太极显示音乐包。评论区的广告又不能屏蔽了。

**Comment by nining377** [comment]
你可以看看xposed的日志有没有报错信息哦

**Comment by T9041** [comment]
太极好像没有日志。。

**Comment by nining377** [comment]
我没有使用太极，太极会有部分功能失效，你可以尝试更新网易云到最新版本
