### ISSUE TITLE
解决UnlockNeteaseMusic模块自动停止运行的问题

### ISSUE THREAD

**Issue by OprtsenLifksl** [nining377/dolby_beta#309]
将node文件添加进网易云音乐安装包/lib/armeabi/内即可重新使用UnlockNeteaseMusic模块（推荐使用MT管理器操作）https://nyxhy.lanzoue.com/is2pN0icu13a（解压后使用）

**Comment by endskp** [comment]
> 

无法解压

**Comment by OprtsenLifksl** [comment]
> > 
> 
> 无法解压

https://nyxhy.lanzoue.com/is2pN0icu13a重新下载即可

**Comment by endskp** [comment]
还是不行，昨天我还好好的，今天就启动卡主界面，试了各种版本的大喇叭和网易云组合，还是卡首屏闪退

**Comment by endskp** [comment]
> > > 
> > 
> > 
> > 无法解压
> 
> [https://nyxhy.lanzoue.com/is2pN0icu13a重新下载即可](https://nyxhy.lanzoue.com/is2pN0icu13a%E9%87%8D%E6%96%B0%E4%B8%8B%E8%BD%BD%E5%8D%B3%E5%8F%AF)

还是不行，昨天我还好的，今天就启动卡主界面，试了各种版本的大召唤和网易云组合，还是卡首屏闪退

**Comment by LeapRay** [comment]
> 将node文件添加进网易云音乐安装包/lib/armeabi/内即可重新使用UnlockNeteaseMusic模块（推荐使用MT管理器操作）[https://nyxhy.lanzoue.com/is2pN0icu13a（解压后使用）](https://nyxhy.lanzoue.com/is2pN0icu13a%EF%BC%88%E8%A7%A3%E5%8E%8B%E5%90%8E%E4%BD%BF%E7%94%A8%EF%BC%89)

请问这种方式最高支持到哪个版本？

**Comment by tyaibnliio** [comment]
使用lsp模块也可以解决吗

**Comment by ldy2333** [comment]
lsp嵌入版利用此方法成功恢复解锁灰色歌曲功能，👍赞

**Comment by laorentou666** [comment]
感谢，本人亲测已经恢复成功了，现在把正在用的版本分享给大家
**已配置libnode并自带杜比大喇叭，下载直装使用即可**（通知栏会弹脚本运行错误，无需理会）

由于本人网易云账号被盗过，不能保证此版本安全性（毕竟是从第三方网站上下载的），介意慎用
---
下载地址https://www.123pan.com/s/PaLRVv-vmBi.html
提取码:lp1T

源包:https://www.123pan.com/s/LV1rVv-FEQUv.html

**Comment by hsichien** [comment]
> 感谢，本人亲测已经恢复成功了，现在把正在用的版本分享给大家 **已配置libnode并自带杜比大喇叭，下载直装使用即可**（通知栏会弹脚本运行错误，无需理会）
> 
> ## 由于本人网易云账号被盗过，不能保证此版本安全性（毕竟是从第三方网站上下载的），介意慎用
> 下载地址[https://www.123pan.com/s/PaLRVv-vmBi.html提取码:lp1T](https://www.123pan.com/s/PaLRVv-vmBi.html%E6%8F%90%E5%8F%96%E7%A0%81:lp1T)
> 
> 源包:https://www.123pan.com/s/LV1rVv-FEQUv.html

请问这版本资源失效怎么解决

**Comment by mario6714** [comment]
> 感谢，本人亲测已经恢复成功了，现在把正在用的版本分享给大家 **已配置libnode并自带杜比大喇叭，下载直装使用即可**（通知栏会弹脚本运行错误，无需理会）
> ## 由于本人网易云账号被盗过，不能保证此版本安全性（毕竟是从第三方网站上下载的），介意慎用
> 
> 下载地址https://www.123pan.com/s/PaLRVv-vmBi.html 提取码:lp1T
> 
> 源包:https://www.123pan.com/s/LV1rVv-FEQUv.html

您好，请问“第三方网站”是什么？

谢谢

**Comment by laorentou666** [comment]
即下方的源包（因为是从bing上找到的，没有从某网站，就是从搜索引擎上找的）

**Comment by laorentou666** [comment]
> > 感谢，本人亲测已经恢复成功了，现在把正在用的版本分享给大家 **已配置libnode并自带杜比大喇叭，下载直装使用即可**（通知栏会弹脚本运行错误，无需理会）
> > ## 由于本人网易云账号被盗过，不能保证此版本安全性（毕竟是从第三方网站上下载的），介意慎用
> > 下载地址https://www.123pan.com/s/PaLRVv-vmBi.html 提取码:lp1T
> > 源包:https://www.123pan.com/s/LV1rVv-FEQUv.html
> 
> 您好，请问“第三方网站”是什么？
> 
> 谢谢

即下方的源包（因为是从bing上找到的，没有从某网站，就是从搜索引擎上找的）
