### ISSUE TITLE
大神，重新安装网易之后获取不了cookie了

### ISSUE THREAD

**Issue by mrdream-wong** [nining377/dolby_beta#32]
版本还是7.0.2.10

**Comment by nining377** [comment]
你是怎么登陆的呢？只有手机号登陆与邮箱登录支持获取cookie，一键登录或者第三方登录是不可以的

**Comment by mrdream-wong** [comment]
手机号啊，获取的时候就弹出获取失败请重新登录

**Comment by mrdream-wong** [comment]
也是按操作重启之后重新登录的，还是不行

**Comment by nining377** [comment]
emmmmm，先标记为bug吧

**Comment by mrdream-wong** [comment]
是不是需要开什么权限啊？

**Comment by nining377** [comment]
不需要权限，你有在用其他模块吗？

**Comment by mrdream-wong** [comment]
已经好了，版本换成7.0.2.20就能正常获取cookie了，不知道是不是软件版本的bug

**Comment by Dfdsfdsf23** [comment]
> 已经好了，版本换成7.0.2.20就能正常获取cookie了，不知道是不是软件版本的bug

你好我这登陆提示服务器错误咋解决？
