### ISSUE TITLE
α版本，点击更新服务器地址就会闪退

### ISSUE THREAD

**Issue by zjszzw** [nining377/dolby_beta#33]
点击更新服务器地址就会闪退，不知道为什么，系统是MIUI12.5，安卓11

**Comment by nining377** [comment]
有没有错误日志？崩溃过后底部会有崩溃提示，点击查看更多日志，然后截一下图

**Comment by zjszzw** [comment]
谢谢，但是我忘了获取日志了，不过昨天已经发现问题所在了，是“太极”的问题，换成了“edxposed”就不会闪退了
