### ISSUE TITLE
大喇叭临时更新点

### ISSUE THREAD

**Issue by luoxingran** [nining377/dolby_beta#341]
非官方，随缘更新，代码看情况会提交fork分支，自用7.2.22，6.0其他版本不在范围内

7.24更新内容:

1.同步维护小组最新脚本
2.添加新播放api，修复无法缓冲
3.一起听解锁研究新方法可能暂时用不了（没测试）
4.添加酷我cookie参数（提供了临时的失效自己抓，不在对cookie方面进行更新）

必须重新释放脚本！！！！

下载地址:https://dolby.lanzoul.com/ivYuG13cgzad
密码：g682

**Comment by CapitalGrin** [comment]
网易云音乐（8.8.30）启动后并未出现设置项。而未修改的3.5.4 release能够正常生效。若是我的使用方法有误烦请告知

**Comment by luoxingran** [comment]
是否使用太极

**Comment by luoxingran** [comment]
> 网易云音乐（8.8.30）启动后并未出现设置项。而未修改的3.5.4 release能够正常生效。若是我的使用方法有误烦请告知

是否使用太极

**Comment by CapitalGrin** [comment]
> > 网易云音乐（8.8.30）启动后并未出现设置项。而未修改的3.5.4 release能够正常生效。若是我的使用方法有误烦请告知
> 
> 是否使用太极 是
无root 使用太极模块 另测试7.2.22同样失效

**Comment by luoxingran** [comment]
> > > 网易云音乐（8.8.30）启动后并未出现设置项。而未修改的3.5.4 release能够正常生效。若是我的使用方法有误烦请告知
> > 
> > 是否使用太极 是
> 无root 使用太极模块 另测试7.2.22同样失效

非官方版本，太极用不了，有签名效验的

**Comment by JOB-MA-OOK** [comment]
可用，👍🏻

**Comment by JOB-MA-OOK** [comment]
修复版什么时候出？
