### ISSUE TITLE
求助：该歌曲无法播放，已暂停

### ISSUE THREAD

**Issue by fbstorm** [nining377/dolby_beta#345]
网易云版本：8.8.45
模块版本：3.5.4
![Screenshot_2023-08-20-06-40-51-22_25d38497d72d75227633ae777c2e0df5](https://github.com/nining377/dolby_beta/assets/100028477/0b98613f-8b4b-4377-8b08-6887d24d1687)
如图所示，下载的和网盘的音乐就可以正常播放，网易云有版权的也可以正常播放，但是无版权的就没法播放。
![Screenshot_2023-08-20-06-46-32-45_25d38497d72d75227633ae777c2e0df5](https://github.com/nining377/dolby_beta/assets/100028477/34ffb5d3-abaa-4975-83f7-befb0b08514b)
没版权的时候就像是这样，默认暂停，点播放就切到能放的歌
同时VIP的歌也没法放，试听一过就切歌

**Comment by mario6714** [comment]
https://github.com/nining377/dolby_beta/pull/342

**Comment by fbstorm** [comment]
> #342

大佬，“参考其他类似项目”能不能指条路，纯小白对这摸不着头脑

**Comment by mario6714** [comment]
> > #342
> 
> 大佬，“参考其他类似项目”能不能指条路，纯小白对这摸不着头脑

If you want similar modules for Netease, i cant, sorry

**Comment by mario6714** [comment]
> > #342
> 
> 大佬，“参考其他类似项目”能不能指条路，纯小白对这摸不着头脑


Maybe this help:

https://github.com/nining377/dolby_beta/actions/runs/5663381961
