### ISSUE TITLE
actions 构建 版本安装错误 

### ISSUE THREAD

**Issue by cmmdwl** [nining377/dolby_beta#346]
actions 构建 版本安装错误  使用的是R安装组件 系统版本miui14.0.5 安卓13 
`Parameter specified as non-null is null: method com.yxer.packageinstalles.core.installer.apks.root.apksRoot.OooO0o0, parameter <set-?>`
使用系统自带安装组件直接报安装包损坏

**Comment by luoxingran** [comment]
请给应用签名后安装软件

**Comment by yxok200** [comment]
> 请给应用签名后安装软件

QAQ要怎么签名

**Comment by mario6714** [comment]
> QAQ要怎么签名

You can use MT Manager for sign the apk
