### ISSUE TITLE
[Feature Request] 兼容自建服务器中的ytdlp

### ISSUE THREAD

**Issue by chuwza** [nining377/dolby_beta#376]
开发者大佬你好，Android版本测试过7.22.2到9.1.0，杜比大喇叭是6月22日版本

我通过这个项目 https://github.com/UnblockNeteaseMusic/server 在NAS上使用docker自建了服务器，使用的音源是
pyncmd ytdlp（试了很多音源，发现pyncmd是必要的，YT Music兜底是最好的，毕竟YouTube版权最多），然后我在手机上放”海来阿木-西楼儿女“这首歌，发现如图提示
![Screenshot_20240708-094123_网易云音乐 (手机)](https://github.com/nining377/dolby_beta/assets/30049891/7cde17fb-1dc4-439d-a2da-bc0a1d764cba)
查看docker日志发现，确实解析了Youtube Music，也没有报错，但是手机上就是放不出。

奇怪的是，Windows端网易云音乐是放得出的，只不过会提示这样一句话，然后就放出来了
![屏幕截图(434)](https://github.com/nining377/dolby_beta/assets/30049891/2d800d8c-5219-41e7-b8b3-bd301d486466)

这是谁的问题呢？和ytdlp音源不兼容的是杜比大喇叭还是Android端网易云呢？

现在临时使用pyncmd migu音源来顶替pyncmd ytdlp，但是用来兜底的migu源不如Youtube Music源，比如”海来阿木-西楼儿女“这首歌migu就没有（再加其他音源的话，反而会有反效果，匹配错误的歌更多了）

**Comment by luoxingran** [comment]
大喇叭只是从服务器上获取你的播放地址，并不是走服务器代理网易的所有流量，所以获取到本地的ytb播放地址还是被墙的不能直接访问

**Comment by chuwza** [comment]
> 大喇叭只是从服务器上获取你的播放地址，并不是走服务器代理网易的所有流量，所以获取到本地的ytb播放地址还是被墙的不能直接访问

好的，非常感谢大佬解答
