### ISSUE TITLE
添加不了脚本路径

### ISSUE THREAD

**Issue by zcc1017** [nining377/dolby_beta#41]
安卓11，选择zip文件时无法找到zip文件，管理器只显示txt等类型文件，无法选择本机全部储存

**Comment by nining377** [comment]
请下载一个第三方资源管理器，如ES等

**Comment by nining377** [comment]
> 安卓11，选择zip文件时无法找到zip文件，管理器只显示txt等类型文件，无法选择本机全部储存

已处理，你可以试试，感谢反馈

**Comment by zcc1017** [comment]
谢谢，已经好使了，真心感谢大佬的努力
