### ISSUE TITLE
获取播放地址失败

### ISSUE THREAD

**Issue by Mercury-bot518** [nining377/dolby_beta#42]
最新版本无法播放，提示播放地址获取失败
![Screenshot_20210313-132040_网易云音乐](https://user-images.githubusercontent.com/79913661/111020197-10ff5480-83ff-11eb-9dba-262a26d27e25.png)

**Comment by Mercury-bot518** [comment]
进入网易云时提示脚本不存在

**Comment by nining377** [comment]
> 进入网易云时提示脚本不存在

请下载脚本

**Comment by nining377** [comment]
> 最新版本无法播放，提示播放地址获取失败
> ![Screenshot_20210313-132040_网易云音乐](https://user-images.githubusercontent.com/79913661/111020197-10ff5480-83ff-11eb-9dba-262a26d27e25.png)

脚本运行成功了吗？

**Comment by Mercury-bot518** [comment]
> > 进入网易云时提示脚本不存在
> 
> 请下载脚本

已经下载了脚本，还是不行
![Screenshot_20210313-135313_杜比大喇叭β版](https://user-images.githubusercontent.com/79913661/111020852-ab619700-8403-11eb-8f36-c5b63c8f0c60.png)

**Comment by Mercury-bot518** [comment]
> > 最新版本无法播放，提示播放地址获取失败
> > ![截图_20210313-132040_网易云音乐](https://user-images.githubusercontent.com/79913661/111020197-10ff5480-83ff-11eb-9dba-262a26d27e25.png)
> 
> 脚本运行成功了吗？

没有提示运行成功

**Comment by Mercury-bot518** [comment]
可以用了

**Comment by boxjohn** [comment]
楼主怎么解决的，我啥都配置好了还是用不了

**Comment by Mercury-bot518** [comment]
> 楼主怎么解决的，我啥都配置好了还是用不了

把两个文件放在同一个目录下，重新选择就可以了
![Screenshot_20210313-153532_MT管理器](https://user-images.githubusercontent.com/79913661/111023127-2d58bc80-8412-11eb-96d5-9857d8fab1e9.png)
