### ISSUE TITLE
成功下載後 音樂長度只有10多秒

### ISSUE THREAD

**Issue by githibppp** [nining377/dolby_beta#43]
原本的歌是有2分多鐘的 請問為什麼會這樣?

**Comment by nining377** [comment]
> 原本的歌是有2分多鐘的 請問為什麼會這樣?

播放没有问题吗？如果播放没问题你可以听完等缓存好了再下载

**Comment by githibppp** [comment]
> > 原本的歌是有2分多鐘的 請問為什麼會這樣?
> 
> 播放没有问题吗？如果播放没问题你可以听完等缓存好了再下载

播放也有問題 也是十多秒之後就會跳轉下一首歌

**Comment by nining377** [comment]
> > > 原本的歌是有2分多鐘的 請問為什麼會這樣?
> > 
> > 
> > 播放没有问题吗？如果播放没问题你可以听完等缓存好了再下载
> 
> 播放也有問題 也是十多秒之後就會跳轉下一首歌

那就是音源匹配出错了，你可能看看代理里的说明
