### ISSUE TITLE
自助打卡闪退 网易云后台播放一段时间后会报错

### ISSUE THREAD

**Issue by Piloteee** [nining377/dolby_beta#44]
1. 手机号密码登录成功获取cookie后，自助打卡链接为红心歌单，打卡数量为500，点击打卡后大喇叭会崩溃闪退。
2. 网易云在锁屏后台播放一段时间后，会提示获取播放源失败之类的提示，具体提示忘记了…

- Redmi K30 5G / Android11 / MIUI12.5 / LSPosed 1.3.3
- 网易云8.1.5 大喇叭2.0.1

**Comment by nining377** [comment]
> 1. 手机号密码登录成功获取cookie后，自助打卡链接为红心歌单，打卡数量为500，点击打卡后大喇叭会崩溃闪退。
> 2. 网易云在锁屏后台播放一段时间后，会提示获取播放源失败之类的提示，具体提示忘记了…
> 
> * Redmi K30 5G / Android11 / MIUI12.5 / LSPosed 1.3.3
> * 网易云8.1.5 大喇叭2.0.1

1.尝试重新登录，只支持邮箱，账号密码登录获取cookie，其他登录方式会获取不到cookie
2.可能是服务被系统回收了，暂时不知道怎么解决，你可以对网易云加锁看看能否改善

**Comment by nining377** [comment]
第二点bug应该已经被修复，更新试试，这个issue先关闭了

**Comment by Piloteee** [comment]
更新2.1.0试试，感谢N总

**Comment by Piloteee** [comment]
> 
> 
> 第二点bug应该已经被修复，更新试试，这个issue先关闭了
更新2.1.0试试，感谢N总
