### ISSUE TITLE
安装node和unblockmusic脚本软件闪退

### ISSUE THREAD

**Issue by FrozenMum** [nining377/dolby_beta#45]
如题，我之前用unblockmusic挺好的，整合了之后好像更麻烦了？

**Comment by nining377** [comment]
太空泛了，无法定位问题，请把你的安卓版本，Xposed类型，网易云版本提交一下

**Comment by d4renk** [comment]
** 解决方案
调用第三方文件管理器，选择文件 **

**Comment by nining377** [comment]
> ** 解决方案
> 调用第三方文件管理器，选择文件 **

新版应该不需要第三方的管理器才对

**Comment by xhjxhk** [comment]
> > **解决方案
> > 调用第三方文件管理器，选择文件**
> 
> 新版应该不需要第三方的管理器才对

**新版确实调用系统文件管理器选择闪退，选择第三方可以**

**Comment by FrozenMum** [comment]
> ** 解决方案
> 调用第三方文件管理器，选择文件 **

确实是要用第三方，安装se浏览器即可解决
