### ISSUE TITLE
node文件放哪里啊

### ISSUE THREAD

**Issue by 710347397** [nining377/dolby_beta#47]
node文件放哪里啊₍₍ (̨̡ ‾᷄ᗣ‾᷅ )̧̢ ₎₎![IMG_20210316_200525.jpg](https://user-images.githubusercontent.com/80759766/111306371-22767580-8626-11eb-9595-349f202bf8ad.jpg)

**Comment by nining377** [comment]
放哪里都可以呀，只要你找得到它

**Comment by 710347397** [comment]
![Screenshot_2021-03-16-21-47-09-735_com.netease.cloudmusic.jpg](https://user-images.githubusercontent.com/80759766/111319763-59538800-8634-11eb-8ee6-d22579d6d18d.jpg)  他为什么提示我node未运行，请保持脚本位置正确啊

**Comment by nining377** [comment]
> ![Screenshot_2021-03-16-21-47-09-735_com.netease.cloudmusic.jpg](https://user-images.githubusercontent.com/80759766/111319763-59538800-8634-11eb-8ee6-d22579d6d18d.jpg) 他为什么提示我node未运行，请保持脚本位置正确啊

你路径没对，下载脚本与node然后在大喇叭里选中即可
