### ISSUE TITLE
太极模块未适配

### ISSUE THREAD

**Issue by xhjxhk** [nining377/dolby_beta#48]
![Screenshot_20210316_234408](https://user-images.githubusercontent.com/80608588/111338733-218b2580-86b2-11eb-9b67-48e293a1acae.jpg)

**Comment by xhjxhk** [comment]
能否签发一个最新版版本号为1.1.0太极适配版

**Comment by xhjxhk** [comment]
![Screenshot_20210317_002818](https://user-images.githubusercontent.com/80608588/111345136-f4417600-86b7-11eb-98fb-3fbb9c8afb27.jpg)

**Comment by nining377** [comment]
所有版本都已过太极审核，你可以更新一下太极适配版本库试试
