### ISSUE TITLE
提示脚本文件不存在

### ISSUE THREAD

**Issue by HeeRo1Yuy** [nining377/dolby_beta#59]
lsp1.2.2，已经下载首页的脚本与node文件，打开代理设置，选择路径，点击文件，程序自动退出，重新打开app，再启动网易，提示脚本文件不存在，多次尝试还是这样子☹

**Comment by nining377** [comment]
> lsp1.2.2，已经下载首页的脚本与node文件，打开代理设置，选择路径，点击文件，程序自动退出，重新打开app，再启动网易，提示脚本文件不存在，多次尝试还是这样子

你可以试试第三方文件管理器

**Comment by HeeRo1Yuy** [comment]
> > lsp1.2.2，已经下载首页的脚本与node文件，打开代理设置，选择路径，点击文件，程序自动退出，重新打开app，再启动网易，提示脚本文件不存在，多次尝试还是这样子
> 
> 你可以试试第三方文件管理器

试了第三方文件管理器，可以了，感谢大神开发这么好的插件

**Comment by nining377** [comment]
> > > lsp1.2.2，已经下载首页的脚本与node文件，打开代理设置，选择路径，点击文件，程序自动退出，重新打开app，再启动网易，提示脚本文件不存在，多次尝试还是这样子
> > 
> > 
> > 你可以试试第三方文件管理器
> 
> 试了第三方文件管理器，可以了，感谢大神开发这么好的插件

嗯呀，要谢我的就帮我点小星星吧
