### ISSUE TITLE
提示您选择的不是zip文件，您选择的不是node文件

### ISSUE THREAD

**Issue by Color-l** [nining377/dolby_beta#60]
![Screenshot_20210323_040444_com huawei filemanager](https://user-images.githubusercontent.com/55428198/112051578-12621700-8b8d-11eb-8c9f-79ef8479d669.jpg)
![Screenshot_20210323_040448_com raincat dolby_beta](https://user-images.githubusercontent.com/55428198/112051592-168e3480-8b8d-11eb-9910-42cf1253c9db.jpg)
![Screenshot_20210323_040506_com huawei filemanager](https://user-images.githubusercontent.com/55428198/112051600-1a21bb80-8b8d-11eb-9dfd-99f742660bdf.jpg)
![Screenshot_20210323_040516_com raincat dolby_beta](https://user-images.githubusercontent.com/55428198/112051608-1d1cac00-8b8d-11eb-92ad-8d9f9b03d8a3.jpg)

**Comment by zanjie1999** [comment]
一加 Android11 同问题  
还是拿Android自带的 文件 来选的

**Comment by nining377** [comment]
试试第三方文件管理器吧

**Comment by Color-l** [comment]
使用了第三方的es文件浏览器，能正常使用了，我的是华为EMUI11系统

**Comment by nining377** [comment]
> 使用了第三方的es文件浏览器，能正常使用了，我的是华为EMUI11系统

嗯呀，能用就好啦

**Comment by zanjie1999** [comment]
修一下啊，百度一下复制粘贴也没多少行啊

**Comment by nining377** [comment]
> 修一下啊，百度一下复制粘贴也没多少行啊
> 1202年了还用老api

能用就行了干嘛要升

**Comment by zanjie1999** [comment]
> > 修一下啊，百度一下复制粘贴也没多少行啊
> > 1202年了还用老api
> 
> 能用就行了干嘛要升

这不就是不能用嘛  
这是工具类

```
package com.cupinkie.metime

import android.content.ContentUris
import android.content.Context
import android.database.Cursor
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.DocumentsContract
import android.provider.MediaStore
import androidx.annotation.RequiresApi
import androidx.core.content.FileProvider
import java.io.File
import java.text.DecimalFormat

object FileUtil {
    fun readFileSize(path: String?): String {
        return readableFileSize(File(path).length())
    }

    fun readableFileSize(size: Long): String {
        if (size <= 0) return "0"
        val units = arrayOf("B", "KB", "MB", "GB", "TB")
        val digitGroups = (Math.log10(size.toDouble()) / Math.log10(1024.0)).toInt()
        return DecimalFormat("#,##0.#")
            .format(size / Math.pow(1024.0, digitGroups.toDouble())) + " " + units[digitGroups]
    }

    /**
     * file --> uri
     * @param context
     * @param file
     *
     * @return
     */
    fun getUriFromFile(context: Context?, file: File?): Uri {
        if (context == null || file == null) {
            throw NullPointerException()
        }
        val uri: Uri
        uri = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            FileProvider.getUriForFile(
                context.applicationContext,
                BuildConfig.APPLICATION_ID + ".fileprovider",
                file
            )
        } else {
            Uri.fromFile(file)
        }
        return uri
    }

    /**
     * 专为Android4.4设计的从Uri获取文件绝对路径，以前的方法已不好使
     */
    @RequiresApi(api = Build.VERSION_CODES.KITKAT)
    fun getPath(context: Context, uri: Uri?): String? {
        if (uri == null) return null

        val isKitKat = Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT

        // DocumentProvider
        if (isKitKat && DocumentsContract.isDocumentUri(context, uri)) {
            // ExternalStorageProvider
            //一些三方的文件浏览器会进入到这个方法中，例如ES
            //QQ文件管理器不在此列
            if (isExternalStorageDocument(uri)) {
                val docId = DocumentsContract.getDocumentId(uri)
                val split = docId.split(":".toRegex()).toTypedArray()
                val type = split[0]
                if ("primary".equals(type, ignoreCase = true)) {
                    return Environment.getExternalStorageDirectory().toString() + "/" + split[1]
                }
            } else if (isDownloadsDocument(uri)) {
                val id = DocumentsContract.getDocumentId(uri)
                val contentUri = ContentUris.withAppendedId(
                    Uri.parse("content://downloads/public_downloads"),
                    java.lang.Long.valueOf(id)
                )
                return getDataColumn(context, contentUri, null, null)
            } else if (isMediaDocument(uri)) {
                val docId = DocumentsContract.getDocumentId(uri)
                val split = docId.split(":")
                val type = split[0]
                var contentUri: Uri? = null
                if ("image" == type) {
                    contentUri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI
                } else if ("video" == type) {
                    contentUri = MediaStore.Video.Media.EXTERNAL_CONTENT_URI
                } else if ("audio" == type) {
                    contentUri = MediaStore.Audio.Media.EXTERNAL_CONTENT_URI
                }
                val selection = "_id=?"
                val selectionArgs = arrayOf(split[1])
                return getDataColumn(context, contentUri, selection, selectionArgs)
            }
        } else if ("content".equals(uri.scheme, ignoreCase = true)) { // MediaStore (and general)
            // Return the remote address
            if (isGooglePhotosUri(uri)) return uri.lastPathSegment
            if (isQQMediaDocument(uri)) {
                val path = uri.path
                val fileDir = Environment.getExternalStorageDirectory()
                val file = File(fileDir, path!!.substring("/QQBrowser".length, path.length))
                return if (file.exists()) file.toString() else null
            }
            return getDataColumn(context, uri, null, null)
        } else if ("file".equals(uri.scheme, ignoreCase = true)) { // File
            return uri.path
        }
        return null
    }

    /**
     * Get the value of the data column for this Uri. This is useful for
     * MediaStore Uris, and other file-based ContentProviders.
     *
     * @param context
     * The context.
     * @param uri
     * The Uri to query.
     * @param selection
     * (Optional) Filter used in the query.
     * @param selectionArgs
     * (Optional) Selection arguments used in the query.
     *
     * @return The value of the _data column, which is typically a file path.
     */
    fun getDataColumn(
        context: Context,
        uri: Uri?,
        selection: String?,
        selectionArgs: Array<String>?
    ): String? {
        var cursor: Cursor? = null
        val column = MediaStore.MediaColumns.DATA
        val projection = arrayOf(column)
        try {
            cursor = context.contentResolver.query(uri!!, projection, selection, selectionArgs, null)
            if (cursor != null && cursor.moveToFirst()) {
                val column_index = cursor.getColumnIndexOrThrow(column)
                return cursor.getString(column_index)
            }
        } finally {
            cursor?.close()
        }
        return null
    }

    fun getRealPathFromURI(context: Context, contentUri: Uri?): String? {
        return getDataColumn(context, contentUri, null, null)
    }

    /**
     * @param uri
     * The Uri to check.
     *
     * @return Whether the Uri authority is ExternalStorageProvider.
     */
    fun isExternalStorageDocument(uri: Uri): Boolean {
        return "com.android.externalstorage.documents" == uri.authority
    }

    /**
     * @param uri
     * The Uri to check.
     *
     * @return Whether the Uri authority is DownloadsProvider.
     */
    fun isDownloadsDocument(uri: Uri): Boolean {
        return "com.android.providers.downloads.documents" == uri.authority
    }

    /**
     * @param uri
     * The Uri to check.
     *
     * @return Whether the Uri authority is MediaProvider.
     */
    fun isMediaDocument(uri: Uri): Boolean {
        return "com.android.providers.media.documents" == uri.authority
    }

    /**
     * 使用第三方qq文件管理器打开
     *
     * @param uri
     *
     * @return
     */
    fun isQQMediaDocument(uri: Uri): Boolean {
        return "com.tencent.mtt.fileprovider" == uri.authority
    }

    /**
     * @param uri
     * The Uri to check.
     *
     * @return Whether the Uri authority is Google Photos.
     */
    fun isGooglePhotosUri(uri: Uri): Boolean {
        return "com.google.android.apps.photos.content" == uri.authority
    }
}
```

然后回调的时候调用
```
val uri = data!!.data
var filePath: String?
if ("file".equals(uri?.scheme, ignoreCase = false)) { //使用第三方应用打开
    filePath = uri?.path
} else if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) { //4.4以后
    filePath = FileUtil.getPath(this, uri)
} else { //4.4以下下系统调用方法
    filePath = FileUtil.getRealPathFromURI(this, uri)
}
Log.v("Sparkle", "文件选择：" + filePath + "")
```

我是用kotlin的，你自己转成java吧（

**Comment by nining377** [comment]
> > > 修一下啊，百度一下复制粘贴也没多少行啊
> > > 1202年了还用老api
> > 
> > 
> > 能用就行了干嘛要升
> 
> 这不就是不能用嘛
> 这是工具类
> 
> ```
> package com.cupinkie.metime
> 
> import android.content.ContentUris
> import android.content.Context
> import android.database.Cursor
> import android.net.Uri
> import android.os.Build
> import android.os.Environment
> import android.provider.DocumentsContract
> import android.provider.MediaStore
> import androidx.annotation.RequiresApi
> import androidx.core.content.FileProvider
> import java.io.File
> import java.text.DecimalFormat
> 
> object FileUtil {
>     fun readFileSize(path: String?): String {
>         return readableFileSize(File(path).length())
>     }
> 
>     fun readableFileSize(size: Long): String {
>         if (size <= 0) return "0"
>         val units = arrayOf("B", "KB", "MB", "GB", "TB")
>         val digitGroups = (Math.log10(size.toDouble()) / Math.log10(1024.0)).toInt()
>         return DecimalFormat("#,##0.#")
>             .format(size / Math.pow(1024.0, digitGroups.toDouble())) + " " + units[digitGroups]
>     }
> 
>     /**
>      * file --> uri
>      * @param context
>      * @param file
>      *
>      * @return
>      */
>     fun getUriFromFile(context: Context?, file: File?): Uri {
>         if (context == null || file == null) {
>             throw NullPointerException()
>         }
>         val uri: Uri
>         uri = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
>             FileProvider.getUriForFile(
>                 context.applicationContext,
>                 BuildConfig.APPLICATION_ID + ".fileprovider",
>                 file
>             )
>         } else {
>             Uri.fromFile(file)
>         }
>         return uri
>     }
> 
>     /**
>      * 专为Android4.4设计的从Uri获取文件绝对路径，以前的方法已不好使
>      */
>     @RequiresApi(api = Build.VERSION_CODES.KITKAT)
>     fun getPath(context: Context, uri: Uri?): String? {
>         if (uri == null) return null
> 
>         val isKitKat = Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT
> 
>         // DocumentProvider
>         if (isKitKat && DocumentsContract.isDocumentUri(context, uri)) {
>             // ExternalStorageProvider
>             //一些三方的文件浏览器会进入到这个方法中，例如ES
>             //QQ文件管理器不在此列
>             if (isExternalStorageDocument(uri)) {
>                 val docId = DocumentsContract.getDocumentId(uri)
>                 val split = docId.split(":".toRegex()).toTypedArray()
>                 val type = split[0]
>                 if ("primary".equals(type, ignoreCase = true)) {
>                     return Environment.getExternalStorageDirectory().toString() + "/" + split[1]
>                 }
>             } else if (isDownloadsDocument(uri)) {
>                 val id = DocumentsContract.getDocumentId(uri)
>                 val contentUri = ContentUris.withAppendedId(
>                     Uri.parse("content://downloads/public_downloads"),
>                     java.lang.Long.valueOf(id)
>                 )
>                 return getDataColumn(context, contentUri, null, null)
>             } else if (isMediaDocument(uri)) {
>                 val docId = DocumentsContract.getDocumentId(uri)
>                 val split = docId.split(":")
>                 val type = split[0]
>                 var contentUri: Uri? = null
>                 if ("image" == type) {
>                     contentUri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI
>                 } else if ("video" == type) {
>                     contentUri = MediaStore.Video.Media.EXTERNAL_CONTENT_URI
>                 } else if ("audio" == type) {
>                     contentUri = MediaStore.Audio.Media.EXTERNAL_CONTENT_URI
>                 }
>                 val selection = "_id=?"
>                 val selectionArgs = arrayOf(split[1])
>                 return getDataColumn(context, contentUri, selection, selectionArgs)
>             }
>         } else if ("content".equals(uri.scheme, ignoreCase = true)) { // MediaStore (and general)
>             // Return the remote address
>             if (isGooglePhotosUri(uri)) return uri.lastPathSegment
>             if (isQQMediaDocument(uri)) {
>                 val path = uri.path
>                 val fileDir = Environment.getExternalStorageDirectory()
>                 val file = File(fileDir, path!!.substring("/QQBrowser".length, path.length))
>                 return if (file.exists()) file.toString() else null
>             }
>             return getDataColumn(context, uri, null, null)
>         } else if ("file".equals(uri.scheme, ignoreCase = true)) { // File
>             return uri.path
>         }
>         return null
>     }
> 
>     /**
>      * Get the value of the data column for this Uri. This is useful for
>      * MediaStore Uris, and other file-based ContentProviders.
>      *
>      * @param context
>      * The context.
>      * @param uri
>      * The Uri to query.
>      * @param selection
>      * (Optional) Filter used in the query.
>      * @param selectionArgs
>      * (Optional) Selection arguments used in the query.
>      *
>      * @return The value of the _data column, which is typically a file path.
>      */
>     fun getDataColumn(
>         context: Context,
>         uri: Uri?,
>         selection: String?,
>         selectionArgs: Array<String>?
>     ): String? {
>         var cursor: Cursor? = null
>         val column = MediaStore.MediaColumns.DATA
>         val projection = arrayOf(column)
>         try {
>             cursor = context.contentResolver.query(uri!!, projection, selection, selectionArgs, null)
>             if (cursor != null && cursor.moveToFirst()) {
>                 val column_index = cursor.getColumnIndexOrThrow(column)
>                 return cursor.getString(column_index)
>             }
>         } finally {
>             cursor?.close()
>         }
>         return null
>     }
> 
>     fun getRealPathFromURI(context: Context, contentUri: Uri?): String? {
>         return getDataColumn(context, contentUri, null, null)
>     }
> 
>     /**
>      * @param uri
>      * The Uri to check.
>      *
>      * @return Whether the Uri authority is ExternalStorageProvider.
>      */
>     fun isExternalStorageDocument(uri: Uri): Boolean {
>         return "com.android.externalstorage.documents" == uri.authority
>     }
> 
>     /**
>      * @param uri
>      * The Uri to check.
>      *
>      * @return Whether the Uri authority is DownloadsProvider.
>      */
>     fun isDownloadsDocument(uri: Uri): Boolean {
>         return "com.android.providers.downloads.documents" == uri.authority
>     }
> 
>     /**
>      * @param uri
>      * The Uri to check.
>      *
>      * @return Whether the Uri authority is MediaProvider.
>      */
>     fun isMediaDocument(uri: Uri): Boolean {
>         return "com.android.providers.media.documents" == uri.authority
>     }
> 
>     /**
>      * 使用第三方qq文件管理器打开
>      *
>      * @param uri
>      *
>      * @return
>      */
>     fun isQQMediaDocument(uri: Uri): Boolean {
>         return "com.tencent.mtt.fileprovider" == uri.authority
>     }
> 
>     /**
>      * @param uri
>      * The Uri to check.
>      *
>      * @return Whether the Uri authority is Google Photos.
>      */
>     fun isGooglePhotosUri(uri: Uri): Boolean {
>         return "com.google.android.apps.photos.content" == uri.authority
>     }
> }
> ```
> 
> 然后回调的时候调用
> 
> ```
> val uri = data!!.data
> var filePath: String?
> if ("file".equals(uri?.scheme, ignoreCase = false)) { //使用第三方应用打开
>     filePath = uri?.path
> } else if (Build.VERSION.SDK_INT > Build.VERSION_CODES.KITKAT) { //4.4以后
>     filePath = FileUtil.getPath(this, uri)
> } else { //4.4以下下系统调用方法
>     filePath = FileUtil.getRealPathFromURI(this, uri)
> }
> Log.v("Sparkle", "文件选择：" + filePath + "")
> ```
> 
> 我是用kotlin的，你自己转成java吧（

恶魔妈妈买面膜，好的
