### ISSUE TITLE
node未成功运行，请到模块内选择正确的脚本与Node路径，若已使用存储重定向等APP请保证网易云音乐也可访问到脚本路径!

### ISSUE THREAD

**Issue by zanjie1999** [nining377/dolby_beta#61]
![Screenshot_20210323-192501](https://user-images.githubusercontent.com/16502567/112139372-a70c5980-8c0d-11eb-8597-cefe1774a9f1.jpg)  

系统Android11，node和zip都用es文件管理器选的，路径显示正常，下载的node的确是64bit

![Screenshot_20210323-192727](https://user-images.githubusercontent.com/16502567/112139568-e175f680-8c0d-11eb-9049-564306b0b476.jpg)

就在sd卡根目录

**Comment by 205687875** [comment]
脚本与node如何获得呢😅😅

**Comment by zanjie1999** [comment]
搞定了，换了一版就可以了XD

**Comment by nining377** [comment]
最喜欢能自己解决问题的孩子啦

**Comment by kettly1260** [comment]
> 搞定了，换了一版就可以了XD

换了个什么啊？我32 64的都试过了

**Comment by huazhaozhe** [comment]
Android 11 MIUI12.5同样遇到了这个问题，路径没有问题，不资道是不是node文件的所有者和权限的问

**Comment by huazhaozhe** [comment]
> Android 11 MIUI12.5同样遇到了这个问题，解压选择`/storage/emulated/0/code/node`路径没有问题，node文件所有者和权限有要求吗

换了以前的版本就可以了
