### ISSUE TITLE
专辑付费歌曲和灰色歌曲的无损音质无法获取

### ISSUE THREAD

**Issue by Hernando-G** [nining377/dolby_beta#65]
专辑付费和灰色歌曲本身有无损音源，但是在线播放和下载下来都只有高音质，有没有办法获取无损音质？
![IMG_20210326_145618](https://user-images.githubusercontent.com/80260842/112595692-bb3a9b80-8e45-11eb-9887-904e95819f76.jpg)

**Comment by nining377** [comment]
请在大喇叭里打勾高音质

**Comment by Hernando-G** [comment]
> 请在大喇叭里打勾高音质



> 请在大喇叭里打勾高音质



> 请在大喇叭里打勾高音质

是勾上的，确实无法获取无损音质，自己点“无损音质”也会自动跳到“极高音质”，下载下来的也是HQ音质
![210419da6e9ab330](https://user-images.githubusercontent.com/80260842/112747661-515af700-8fe9-11eb-8f52-91b231aef625.jpg)
