### ISSUE TITLE
歌曲打卡功能失效，只有自助打卡能用

### ISSUE THREAD

**Issue by LittleRey** [nining377/dolby_beta#8]
歌曲打卡功能失效，只有自助打卡能用

**Comment by nining377** [comment]
> 歌曲打卡功能失效，只有自助打卡能用

歌曲打卡不是失效，而是原理为获取推荐歌单来打卡，因为重复打同一首歌是不计入播放量的，所以模块本身带有去重功能，当你的推荐歌单里全是已打卡歌曲自然就失效了哦（PS.这也是为啥那些打卡网站一开始效果很好，到后面效果越来越差甚至播放量不涨的原因，因为没去重，给你打到相同歌曲，不计入播放量中）

**Comment by LittleRey** [comment]
我知道，这个歌单问题应该如何解决呢

**Comment by LittleRey** [comment]
可不可以借助一下别的打卡源码的打卡方式

**Comment by LittleRey** [comment]
或者建立一个api，提供打卡功能

**Comment by nining377** [comment]
> 我知道，这个歌单问题应该如何解决呢

这时候只能依靠自助打卡了，因为推荐歌单是契合你的听歌习惯的，如果自动打卡采用其他api获取歌单歌曲则有可能获取到的歌曲不是你平时听的风格，到时候会造成FM推荐混乱
