### ISSUE TITLE
自助打卡页面问题

### ISSUE THREAD

**Issue by 2051783131** [nining377/dolby_beta#9]
填入cookie后字段太长，底下一部分显示不了![IMG_20200705_180658](https://user-images.githubusercontent.com/67429400/86530340-99ca0600-beea-11ea-8e33-006c8317f398.jpg)
设置改了最小宽度才解决。![IMG_20200705_182004.jpg](https://user-images.githubusercontent.com/67429400/86530664-06de9b00-beed-11ea-8099-6aa5a978a880.jpg)页面改为可滑动的可能更方便

**Comment by nining377** [comment]
好的， 下个版本会修复
