### ISSUE TITLE
最新版网易云无法启动 node

### ISSUE THREAD

**Issue by aviraxp** [nining377/dolby_beta#92]
见 https://stackoverflow.com/questions/62391811/android-10-alternative-to-launching-executable-as-subproccess-stored-in-app-ho

对 target sdk 大于 29 的应用，现在启动 node 的方式会被 selinux 拦截。可能需要回到之前从 sdcard 启动的方式。

**Comment by 1955782864** [comment]
怎么解决呢

**Comment by TsXor** [comment]
我看了termux由于API29的限制而引发的讨论帖。之前看的时候没登录，所以中间的没看到，我看见核心开发者@xeffyr的态度发生了很大变化，一开始是能用就行，最后决定拥护谷歌的“app只能执行内置在apk中的文件”，结果后来有很多完全可以采用的方法都被抛弃了。

说回正题，在那个帖的末几个评论里，有人提到/data/user_de/[应用包名]在android 11 beta中还是可读可写可执行的，而且测试发现确实可以。这样的话，直接把执行目录换到/data/user_de/[应用包名]还可以撑个至少一年。

那个帖里提到的其他方法：用proot（有效率损失），用用户空间链接器（我也不知道这是什么，直译的）劫持execve调用。

当然，还有一个最合适的方法：把node装进lib文件夹。说到底，dolby beta不是termux。termux需要“随时安装新可执行文件”的能力，但dolby beta不需要。这样做唯一的缺点就是如果要更新node，就要更新app。但是我觉得node其实能用就行，不必经常更新。就算我觉得的是错的，源搁着开着呢，可以找别人更新啊🤔

**Comment by aviraxp** [comment]
这样需要用模块自己的context运行node，网易云不一定能识别到

**Comment by TsXor** [comment]
执行目录换到/data/user_de/0/[包名]     （低语）
以及，能不能介绍下从sdcard启动是怎么启动的？sdcard不是noexec吗？

**Comment by aviraxp** [comment]
我看错了，unblockneteasemusic同样是复制到网易云的data再执行
